name: release-build

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches: [rust]
    tags:
      - v[0-9]+.*

jobs:
  build-win-mac:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
      name: ${{ matrix.os }}
      runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/create-gh-release-action@v1
        with:
          # (Optional) Path to changelog.
          # changelog: CHANGELOG.md
          # (Optional) Create a draft release.
          # [default value: false]
          draft: true
          title: $version
        env:
          # (Required) GitHub token for creating GitHub Releases.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}