name: release-build

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/create-gh-release-action@v1
        with:
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  upload-assets:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install linux lib
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install libxcb-shape0-dev libxcb-xfixes0-dev
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: electron-icon-builder
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
